app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Auth route
Route::auth();

// Attach routes to the appropriate controllers.
Route::get('/', 'HomeController@index');
Route::resource('/home', 'HomeController');
Route::resource('/projectIdeas', 'IdeasController');
Route::resource('/projectExamples', 'ExamplesController');
Route::resource('/images', 'ImagesController');
Route::resource('/users', 'UsersController');
Route::resource('/likes', 'LikesController');
Route::resource('/filter', 'FilterController');
Route::resource('/categorys', 'CategorysController');

app/Idea.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Idea extends Model
{
    //Use the ideas table within the database.
    protected $table = 'ideas';

    //Allow the title, description, likes, category_id and owner fields to be filled with data.
    protected $fillable = [
    	'title', 'description', 'likes', 'category_id', 'owner'
    ];

    //Create a relationship to the category attached to the project ideas so it can be displayed within the view.
    public function category()
    {
    	return $this->hasOne('App\Category', 'id', 'category_id');
    }

    //Create a relationship with the diffrent project examples attached to the project idea so they can be accessed within the view.
    public function examples()
    {
    	return $this->hasMany('App\Example', 'project_id');
    }

    //Create a relationship with the user that owns the project idea so this can be accessed within the view.
    public function user()
    {
        return $this->hasOne('App\User', 'id', 'owner');
    }
}

app/Http/Controllers/IdeasController.php
<?php

namespace App\Http\Controllers;

//Load requirements for the controller.
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Idea;
use App\User;
use App\Category;
use Auth;

class IdeasController extends Controller
{
    //Check to see if the user is logged in or not.
    public function __construct()
    {
        $this->middleware('auth');
    }

    /* When the default (/projectIdeas) or project ideas list route is requisted return the project ideas overview with all the project ideas stored in the database so they can be displayed in the application. Return the logged in user for use within the view and categoryies for use within the filter form. */
    public function index()
    {
        $user = User::findORFail(Auth::user()->id);
        $ideas = Idea::all();
        $categorys = Category::lists('category', 'id');
        return view('ideas.list', ['ideas' => $ideas])->with(['user' => $user])->with(['categorys' => $categorys]);
    }

    /* Used to return the show view for a project idea. First find the logged in user and then find the appropriate idea based on the ID provided and return these to the show view */
    public function show($id)
    {
        $user = User::findORFail(Auth::user()->id);
        $idea = Idea::findORFail($id);
        return view('ideas.show', ['idea' => $idea])->with(['user' => $user]);
    }

    /* Used to return the edit function. First find the logged in user then find the idea based on the ID provided. Then return a list of all the categoryies and also their id's for used within the form. Return the edit view with the relevant idea, logged in user and categories. */
    public function edit($id)
    {
        $user = User::findORFail(Auth::user()->id);
        $idea = Idea::findORFail($id);
        $categorys = Category::lists('category', 'id');
        return view('ideas.edit', ['idea' => $idea])->with(['user' => $user])->with(['categorys' => $categorys]);
    }

    /* Used to update the project idea within the database. First find the relevant idea within the database using the id provided. Then update this idea using the information provided by the user. Finally redirect the user to the project show page for the updated project idea. */
    public function update(Requests\UpdateIdeaRequest $request, $id)
    {
        $idea = Idea::findORFail($id);

        $idea->update([
            'title' => $request->get('title'),
            'description' => $request->get('description'),
            'category_id' => $request->get('category')
        ]);

        return \Redirect::route('projectIdeas.show', $id)->with('message', $request->get('title') . ' has been successfully updated!');
    }

    /* Return the create view for the user. First find the logged in user within the database, then return a list of all the categories names and also id's. Finally return the project idea create view with the logged in user and categories for use within the form. */
    public function create()
    {
        $user = User::findORFail(Auth::user()->id);
        $categorys = Category::lists('category', 'id');

        return view('ideas.create', ['user' => $user])->with(['categorys' => $categorys]);
    }

    /* Used for storing the new project idea within the database. First create a new instance of the idea model and store this in a variable, then find the logged in user and store this within a variable. Add the information gathered from the user to the idea model, setting the owner to the retrieved user and the likes to 0. Save the idea and redirect the user to the project ideas overview page with a message to let them know their action was successful */
    public function store(Requests\CreateIdeaRequest $request)
    {
        $idea = new Idea;
        $user = Auth::user()->id;

        $idea->title = $request->title;
        $idea->description = $request->description;
        $idea->owner = $user;
        $idea->likes = 0;
        $idea->category_id = $request->category;

        $idea->save();

        return \Redirect::route('projectIdeas.index')->with('message', ' has been successfully created!'); 
    }

    /* Used to delete a project idea from the database. Find the idea using the id provided and destroy this record, returning the user to the project ideas overview page with a message to let them know their action was successful. */
    public function destroy($id)
    {
        Idea::destroy($id);

        return \Redirect::route('projectIdeas.index')->with('message', 'has been successfully deleted!'); 
    }
}

resources/views/ideas/create.blade.php
<!-- Load in master layout -->
@extends('layouts.master')

<!-- Set page title -->
@section('title') Login @endsection

@section('content')
<div class="container">

    <!-- If the user is a student then dont allow them to see the create project example form and return message to let them know they dont have access -->
	@if($user->accesslevel == 1)
		<p class="lead">You don't have access to this page.</p>
	@else
    <!-- Create a form for adding a new project idea styled with Bootstrap CSS. Form wil post to the project ideas controller where it will be handeled. -->  
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">Submit your project idea:</div>
                <div class="panel-body">
                	{!! Form::open(array('url' => 'projectIdeas')) !!}
                		<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                			{!! Form::label('title', 'Project Title:', array('class' => 'formLabel')) !!}
                			{!! Form::text('title', 'Project title...', array('class' => 'form-control')) !!}
                            @if ($errors->has('title'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('title') }}</strong>
                                </span>
                            @endif
                		</div>
                		<div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                			{!! Form::label('description', 'Description:', array('class' => 'formLabel')) !!}
                			{!! Form::textarea('description', 'Project description...', array('class' => 'form-control', 'row' => '5')) !!}
                            @if ($errors->has('description'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </span>
                            @endif
                		</div>
                		<div class="form-group">
                			{!! Form::label('category', 'Category:', array('class' => 'formLabel')) !!}
                			{!! Form::select('category', $categorys, null, array('class' => 'form-control')) !!}
                            <p class="formHelp"><small><mark>> Cant find the category your looking for? <a href="{{ route('categorys.create') }}" class="normalLinks">Click here to make a new one</a></mark></small></p>
                		</div>
                		<div class="form-group">
                			<div class="formButtons">
	                			{!! Form::submit('Create project', array('class' => 'btn btn-success btn-block')) !!}
                                <!-- Add a cancel button for the user if they require it, they will be redirected to the project ideas overview page -->
	                			<div class="cancelButton"><a href="{{ url('/projectIdeas') }}" class="btn btn-danger btn-block">Cancel</a></div>
                			</div>
                		</div>
                	{!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    @endif
</div>
@endsection

resources/views/ideas/edit.blade.php
<!-- Load in master layout -->
@extends('layouts.master')

<!-- Set page title -->
@section('title') Login @endsection

@section('content')
<div class="container">

    <!-- If the user is a student then dont allow them to see the edit project example form and return message to let them know they dont have access -->
	@if($user->accesslevel == 1)
		<p class="lead">You don't have access to this page.</p>
	@else
    <!-- Create a form for editing a project idea styled with Bootstrap CSS. Form wil post to the project ideas controller where it will be handeled. --> 
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">{{ $idea->title }}</div>
                <div class="panel-body">
                	{!! Form::model($idea, array('route' => array('projectIdeas.update', $idea->id), 'method' => 'put')) !!}
                		<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                			{!! Form::label('title', 'Project Title:', array('class' => 'formLabel')) !!}
                			{!! Form::text('title', $idea->title, array('class' => 'form-control')) !!}
                            @if ($errors->has('title'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('title') }}</strong>
                                </span>
                            @endif
                		</div>
                		<div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                			{!! Form::label('description', 'Description:', array('class' => 'formLabel')) !!}
                			{!! Form::textarea('description', $idea->description, array('class' => 'form-control', 'row' => '5')) !!}
                            @if ($errors->has('description'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('description') }}</strong>
                                </span>
                            @endif
                		</div>
                		<div class="form-group">
                			{!! Form::label('category', 'Category:', array('class' => 'formLabel')) !!}
                			{!! Form::select('category', $categorys, $idea->category->category, array('class' => 'form-control')) !!}
                		</div>
                		<div class="form-group">
                			<div class="formButtons">
	                			{!! Form::submit('Update project', array('class' => 'btn btn-success btn-block')) !!}
                                <!-- Add a cancel button for the user if they require it, they will be redirected to the project ideas overview page -->
	                			<div class="cancelButton"><a href="{{ url('/projectIdeas') }}" class="btn btn-danger btn-block">Cancel</a></div>
                			</div>
                		</div>
                	{!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    @endif
</div>
@endsection

resources/views/ideas/list.blade.php
<!-- Load in master layout -->
@extends('layouts.master')

<!-- Set page title -->
@section('title') Project Ideas @endsection

@section('content')

<div class="container">
	<!-- If a message has been set display it to the user. -->
	@if(Session::get('message'))
	    <div class="alert alert-success">
	        <strong>Project idea: </strong>{{ Session::get('message') }}
	    </div>
	@endif
	<!-- Introduce the user to the page. -->
	<div class="row">
	    <div class="col-md-12">
	        <h1>Project Ideas</h1>
	        <p class="lead">This page will present project ideas that members of staff have approved and submitted to this web application. This will allow for you to browse through multiple different project suggestions so that you can begin to get an understanding of what type of project you would like to undertake for your final year project. If you see a project you like then click the project title to view more information about that given project. If you would like to see the member of staff’s profile to see other projects they have submitted then please click the name located in the created by column. If you see a project you like then express your interest and click the like button!</p>
	    </div>
	</div>
	<!-- Create a filter function so the users can see project only by specified category. Create a button for adding a project idea if the user if staff or an admin and add a button for all users for viewing all project examples. -->
	<div class="row">
		<div class="col-md-6 filterByCategory">
			<div class="filterByCategory">
				{!! Form::open(array('route' => 'filter.store', 'class' => 'form-inline')) !!}
					{!! Form::label('category', 'Filter by category:', array('class' => 'formLabel')) !!}
	                {!! Form::select('category', $categorys, null, array('class' => 'form-control')) !!}
	                {!! Form::submit('Apply', array('class' => 'btn btn-success')) !!}
				{!! Form::close() !!}
			</div>
		</div>
		<div class="col-md-6">
			<p>
				@if($user->accesslevel != 1)
					<a href="{{ route('projectIdeas.create') }}" class="btn btn-success"><i class="fa fa-btn fa-plus-circle"></i>Add new project idea</a>
				@endif
				<a href="{{ url('/projectExamples') }}" class="btn btn-primary">View all project examples</a>
			</p>
		</div>
	</div>
	<!-- Create a table to display all the project ideas and add edit and delete function for admins. If there is no content set them inform the user. -->
	<table class="table table-hover">
		@if(count($ideas) >= 1)
			<tr>
				<th>Project title</th>
				<th>Category</th>
				<th>Last updated</th>
				<th>Submitted by</th>
				<th>Likes</th>
				@if($user->accesslevel == 3)
					<th></th>
					<th></th>
				@endif
			</tr>
			@foreach($ideas as $idea)	
				<tr>
					<td><a href="{{ route('projectIdeas.show', [$idea->id]) }}" class="normalLinks">{{ $idea->title }}</a></td>
					<td>{{ $idea->category->category }}</td>
					<td>{{ date('d, F, Y', strtotime($idea->updated_at)) }}</td>
					<td><a href="{{ route('users.show', [$idea->user->id]) }}" class="normalLinks">{{ $idea->user->name }}</a></td>
					<td>{{ $idea->likes }}</td>
					@if($user->accesslevel == 3)
						<td><a href="{{ route('projectIdeas.edit', [$idea->id]) }}" class="btn btn-success"><i class="fa fa-btn fa-edit"></i>Edit</a></td>
						<td>
							{!! Form::model($idea, array('route' => array('projectIdeas.destroy', $idea->id), 'method' => 'delete', 'onsubmit' => 'return ConfirmDelete()')) !!}
								{!! Form::hidden('_method', 'DELETE') !!}
	                    		{!! Form::submit('Delete', array('class' => 'btn btn-danger')) !!}
							{!! Form::close() !!}
	                    </td>
					@endif
				</tr>
			@endforeach
		@else
			<tr>
				<td><h3>There is no projects for that category please select a diffrent one or click the Project Ideas link to view all.</h3></td>
			</tr>
		@endif
	</table>
</div>

@endsection

resources/views/ideas/show.blade.php
<!-- Load in master layout -->
@extends('layouts.master')

<!-- Set page title -->
@section('title') {{ $idea->title }} @endsection

@section('content')

<div class="container">
	<!-- If there is a message set then display it to the user. -->
	@if(Session::get('message'))
	    <div class="alert alert-success">
	        <strong>Project idea: </strong>{{ Session::get('message') }}
	    </div>
	@endif
	<!-- Use title to create page title followed by category, submitted by and last updated information. Format the date so it it more user friendly. -->
	<div class="row">
	    <div class="col-md-9">
	    	<h1>{{ $idea->title }}</h1>
			<p class="lead"><strong>Category: </strong>{{ $idea->category->category }}</p>
	    	<p class="lead"><strong>Submitted by: </strong><a href="{{ route('users.show', [$idea->user->id]) }}" class="normalLinks">{{ $idea->user->name }}</a></p>
	    	<p class="lead"><strong>Last updated: </strong>{{ date('d, F, Y', strtotime($idea->updated_at)) }}</p>
		</div>
		<div class="col-md-3">
			<!-- If the user owns the project or they are an admin let them have an edit and delete option. -->
			<div class="ideaShowButtons">
				@if($user->accesslevel == 1)	
					
				@elseif($idea->owner == $user->id || $user->accesslevel == 3)
					<a href="{{ route('projectIdeas.edit', [$idea->id]) }}" class="btn btn-success"><i class="fa fa-btn fa-edit"></i>Edit</a>
					{!! Form::model($idea, array('route' => array('projectIdeas.destroy', $idea->id), 'method' => 'delete', 'class' => 'deleteButton', 'onsubmit' => 'return ConfirmDelete()', )) !!}
						{!! Form::hidden('_method', 'DELETE') !!}
	                    {!! Form::submit('Delete', array('class' => 'btn btn-danger', 'id' => 'delete')) !!}
					{!! Form::close() !!}	
				@endif
			</div>
		</div>
	</div>
	<!-- Present the project description and the example attached to the project idea. If there is not any project examples assigned then inform the user. -->
	<div class="row">
		<div class="col-md-6">
			<h3>Description</h3>
			<p>{{ $idea->description }}</p>
		</div>
		<div class="col-md-6">
			<h3>Example</h3>
			@if ( !$idea->examples->count() )
				<p class="lead">There is currently no examples linked to this project.</p>
       	 	@else
       	 		@foreach($idea->examples as $example)
       	 			@foreach($example->images as $image)
						<img src="{{ $image->path }}" class="projectExample">
					@endforeach
					<p class="lead"><strong>Grade achieved for example above: </strong>{{ $example->grade }}</p>
				@endforeach
			@endif
		</div>
	</div>
	<!-- Add a likes button so users can show their interest in a project. -->
	<div class="row">
		<div class="col-md-12">
			<a href="{{ route('likes.edit', [$idea->id]) }}" class="btn btn-info"><i class="fa fa-btn fa-thumbs-up"></i>{{ $idea->likes }}</a>
		</div>
	</div>
</div>

@endsection