app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Auth route
Route::auth();

// Attach routes to the appropriate controllers.
Route::get('/', 'HomeController@index');
Route::resource('/home', 'HomeController');
Route::resource('/projectIdeas', 'IdeasController');
Route::resource('/projectExamples', 'ExamplesController');
Route::resource('/images', 'ImagesController');
Route::resource('/users', 'UsersController');
Route::resource('/likes', 'LikesController');
Route::resource('/filter', 'FilterController');
Route::resource('/categorys', 'CategorysController');

app/Example.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Example extends Model
{
    //Use the examples table within the database.
    protected $table = 'examples';

    //Allow the project_id and grade fields to be filled with data.
    protected $fillable = [
    	'project_id', 'grade'
    ];

    /* Create a relationship between the project examples and the project example images that are attached to this project example so they can be accessed in the view and displayed to the user. */
    public function images()
    {
    	return $this->hasMany('App\ProjectExampleImages', 'example_id', 'id');
    }

    //Create a relationship between the project example and the project idea it belongs to. This will allow the idea to be accessed from within the view.
    public function idea()
    {
    	return $this->hasOne('App\Idea', 'id', 'project_id');
    }
}

app/Http/Controllers/ExamplesController.php
<?php

namespace App\Http\Controllers;

//Load requirements for the controller.
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Idea;
use App\User;
use App\ProjectExampleImages;
use App\Example;
use Auth;


class ExamplesController extends Controller
{
    //Check to see if the user is logged in or not
    public function __construct()
    {
        $this->middleware('auth');
    }

    /* When the default route (/projectExamples) or list view is requested return the overview of all the project examples. All examples are sent to the view along with the logged in user. */
    public function index()
    {
        $user = User::findORFail(Auth::user()->id);
        $examples = Example::all(); 
        return view('examples.list', ['examples' => $examples])->with(['user' => $user]);
    }

    //Used to return the edit interface to the user. The logged in user is sent with the example that is being edited for use within the view.
    public function edit($id)
    {
        $user = User::findORFail(Auth::user()->id);
        $example = Example::findORFail($id);
        return view('examples.edit', ['example' => $example])->with(['user' => $user]);
    }

    /* Used to update the project example within the database. First find the relevant example with the id provided from the request, then update it with the new grade gathered from the user. Check to see if an image has been uploaded, if it has then create a new project example images model to store the new image within the project example images table. Get the id from the example previously found within the database and then store the file path using the default route (/images/) and also the file name to create a working file path to the image which can be loaded in the view. Move the image to the correct folder and save the new project example images model. Return the user to the project examples overview page with a message to let them know their actions was successful. */
    public function update(Requests\UpdateExampleRequest $request, $id)
    {
        $example = Example::findORFail($id);

        $example->update([
            'grade' => $request->get('grade')
        ]);

        if($request->image != null){
            $exampleImage = new ProjectExampleImages;
            $exampleImage->example_id = $id;
            $file = array('image' => $request->image);

            $path = 'images/';
            $fileName = $request->image->getClientOriginalName();
            $fullFilePath = '/images/' . $fileName;

            $request->image->move($path, $fileName);

            $exampleImage->path = $fullFilePath;

            $exampleImage->save();

            return \Redirect::route('projectExamples.index')->with('message', ' has been successfully updated!');
        }

        return \Redirect::route('projectExamples.index')->with('message', ' has been successfully updated!');    
    }

    /* Used for returning the interface for adding a new project example. Include the logged in user and a list of only the project ideas title and id within a variable for use in the view. */
    public function create()
    {
        $user = User::findORFail(Auth::user()->id);
        $ideas = Idea::lists('title', 'id');

        return view('examples.create', ['user' => $user])->with(['ideas' => $ideas]);
    }

    /* Used to store the new project example within the database. First create a new instance of an example model. Then get the information from the user and use it to fill the model and finally save the new record to the database. Create a new instance of the project example images model to store the example that is attached to the project idea. Get the example id by using the example previously saved then use the default image path along with the file name to create a working file path for use within the view to display the image. Move the image to the correct folder and save the new project example images model. Return the user to the project examples overview page with a message to let them know their action was successful */
    public function store(Requests\CreateExampleRequest $request)
    {
        $example = new Example;

        $example->project_id = $request->idea;
        $example->grade = $request->grade;

        $example->save();

        $exampleImage = new ProjectExampleImages;
        
        $exampleImage->example_id = $example->id;
        $file = array('image' => $request->image);
        $path = 'images/';
        $fileName = $request->image->getClientOriginalName();
        $fullFilePath = '/images/' . $fileName;

        $request->image->move($path, $fileName);

        $exampleImage->path = $fullFilePath;

        $exampleImage->save();

        return \Redirect::route('projectExamples.index')->with('message', ' has been successfully submitted!');   
    }

    /* Find the appropriate example within the database using the id provided and destroy the record. Return the user to the project examples overview page with a message to let them know their action was successful. */
    public function destroy($id)
    {
        Example::destroy($id);

        return \Redirect::route('projectExamples.index')->with('message', 'has been successfully deleted!'); 
    }
}

resources/views/examples/create.blade.php
 <!-- Load in master layout -->
@extends('layouts.master')

<!-- Set page title -->
@section('title') Create new project example @endsection

@section('content')
<div class="container">

    <!-- If the user is a student then dont allow them to see the create project example form and return message to let them know they dont have access -->
	@if($user->accesslevel == 1)
		<p class="lead">You don't have access to this page.</p>
	@else
    <!-- Create a form for adding a new project example styled with Bootstrap CSS. Form wil post to the project examples controller where it will be handeled. --> 
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">Create new project example:</div>
                <div class="panel-body">
                	{!! Form::open(array('route' => 'projectExamples.store', 'files' => true)) !!}
                		<div class="form-group">
                			{!! Form::label('grade', 'Grade achieved:', array('class' => 'formLabel')) !!}
                			{!! Form::select('grade', array('First' => 'First', '2:1' => '2:1', '2:2' => '2:2'), null, array('class' => 'form-control')) !!}
                		</div>
                		<div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                			{!! Form::label('image', 'Add new image:', array('class' => 'formLabel')) !!}
                			{!! Form::file('image', array('class' => 'form-control')) !!}
                            @if ($errors->has('image'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('image') }}</strong>
                                </span>
                            @endif
                		</div>
                		<div class="form-group">
                			{!! Form::label('idea', 'Attach to project suggestion:', array('class' => 'formLabel')) !!}
                			{!! Form::select('idea', $ideas, null, array('class' => 'form-control')) !!}
                		</div>
                		<div class="form-group">
                			<div class="formButtons">
	                			{!! Form::submit('Create example', array('class' => 'btn btn-success btn-block')) !!}
                                <!-- Add a cancel button so the user can cancel the action if they want to and return them to the project examples overview page. -->
	                			<div class="cancelButton"><a href="{{ url('/projectExamples') }}" class="btn btn-danger btn-block">Cancel</a></div>
                			</div>
                		</div>
                	{!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    @endif
</div>
@endsection

resources/views/examples/edit.blade.php
<!-- Load in master layout -->
@extends('layouts.master')

<!-- Set page title -->
@section('title'){{ $example->idea->title }} - Example | Edit @endsection

@section('content')
<div class="container">

    <!-- If the user is a student then dont allow them to see the edit project example form and return message to let them know they dont have access -->
	@if($user->accesslevel == 1)
		<p class="lead">You don't have access to this page.</p>
	@else 
    <!-- Create a form for editing a project example styled with Bootstrap CSS. Form wil post to the project examples controller where it will be handeled. -->
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
                <div class="panel-heading">{{ $example->idea->title }} - Example | Edit</div>
                <div class="panel-body">
                	{!! Form::model($example, array('route' => array('projectExamples.update', $example->id), 'method' => 'put', 'files' => 'true')) !!}
                		<div class="form-group">
                			{!! Form::label('grade', 'Grade achieved:', array('class' => 'formLabel')) !!}
                			{!! Form::select('grade', array('First' => 'First', '2:1' => '2:1', '2:2' => '2:2'), null, array('class' => 'form-control')) !!}
                		</div>
                		<div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                			{!! Form::label('image', 'Add new image:', array('class' => 'formLabel')) !!}
                			{!! Form::file('image', array('class' => 'form-control')) !!}
                            @if ($errors->has('image'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('image') }}</strong>
                                </span>
                            @endif
                		</div>
                		<div class="form-group">
                			<div class="formButtons">
	                			{!! Form::submit('Update example', array('class' => 'btn btn-success btn-block')) !!}
                                <!-- Add a cancel button so the user can cancel the action if they want to and return them to the project examples overview page. -->
	                			<div class="cancelButton"><a href="{{ url('/projectExamples') }}" class="btn btn-danger btn-block">Cancel</a></div>
                			</div>
                		</div>
                	{!! Form::close() !!}
                    <!-- Show the images currently attached to this project example and provide a delete button. -->
                    <div class="form-group">
                        <h4 class="formLabel">Current images:</h4>
                        @foreach($example->images as $image)
                            <img src="{{ $image->path }}" class="exampleEditImages">
                            {!! Form::model($image, array('route' => array('images.destroy', $image->id), 'method' => 'delete', 'onsubmit' => 'return ConfirmDelete()')) !!}
                                {!! Form::hidden('_method', 'DELETE') !!}
                                {!! Form::submit('Delete', array('class' => 'btn btn-danger')) !!}
                            {!! Form::close() !!}
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
    @endif
</div>
@endsection

resources/views/examples/list.blade.php
<!-- Load in master layout -->
@extends('layouts.master')

<!-- Set page title -->
@section('title') Project Examples @endsection

@section('content')

<div class="container">
	<!-- If a message is set display it to the user. -->
	@if(Session::get('message'))
	    <div class="alert alert-success">
	        <strong>Project example: </strong>{{ Session::get('message') }}
	    </div>
	@endif
	<!-- Introduce the user to the page. -->
	<div class="row">
	    <div class="col-md-12">
	        <h1>Project Examples</h1>
	        <p class="lead">Project examples are displayed below, these are all previous projects that students have submitted for their final year projects. The grade that they achieved for the submitted project is also included so that you can get a feel of the ammount of work you will need to undertake in order to be able to achieve your desired grade. There are various different examples for the various project ideas, to see more information about an example please click the project title which will take you to a more indepth view about that project.</p>
	    </div>  
	</div>
	<!-- Add a button for creating a project example if the user is staff or an admin. Add another button for all users to see all project suggestions. -->
	<div class="row">
		<div class="col-md-12">
			<p>
				@if($user->accesslevel != 1)
				<a href="{{ route('projectExamples.create') }}" class="btn btn-success"><i class="fa fa-btn fa-plus-circle"></i>Add new project example</a>
				@endif
				<a href="{{ url('/projectIdeas') }}" class="btn btn-primary">View all project suggestions</a>
			</p>
		</div>
	</div>
	<!-- Loop over all the project examples displaying them to the user with the project title to accompany it. Include the grade achieved for the example below the images. -->
	<div class="row">
		@foreach($examples as $example)
		    <div class="col-md-6">
		    	<h2><a href="{{ route('projectIdeas.show', [$example->idea->id]) }}" class="normalLinks">{{ $example->idea->title }}</a></h2>
		    	@if($user->accesslevel == 1)	
					
				@elseif($example->idea->owner == $user->id || $user->accesslevel == 3)
					<a href="{{ route('projectExamples.edit', [$example->id]) }}" class="btn btn-success"><i class="fa fa-btn fa-edit"></i>Edit</a></td>
					{!! Form::model($example, array('route' => array('projectExamples.destroy', $example->id), 'method' => 'delete', 'class' => 'deleteButton', 'onsubmit' => 'return ConfirmDelete()')) !!}
						{!! Form::hidden('_method', 'DELETE') !!}
                    	{!! Form::submit('Delete', array('class' => 'btn btn-danger')) !!}
					{!! Form::close() !!}
				@endif
		    	@foreach($example->images as $image)
		    		<img src="{{ $image->path }}" class="projectExample">
		    	@endforeach
		    	<p class="lead"><strong>Grade achieved for project example above: </strong>{{ $example->grade }}</p>
		    </div>
	    @endforeach
	</div>
</div>

@endsection