app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Auth route
Route::auth();

// Attach routes to the appropriate controllers.
Route::get('/', 'HomeController@index');
Route::resource('/home', 'HomeController');
Route::resource('/projectIdeas', 'IdeasController');
Route::resource('/projectExamples', 'ExamplesController');
Route::resource('/images', 'ImagesController');
Route::resource('/users', 'UsersController');
Route::resource('/likes', 'LikesController');
Route::resource('/filter', 'FilterController');
Route::resource('/categorys', 'CategorysController');

resources/views/layouts/footer.blade.php
<footer class="footer">
    <div class="container">
        <!-- Add a signature and some quick links for users who are logged in. Depending on what user level they are will depend on what links they will see with admins having a quicklink to all the applications features. -->
    	<div class="col-md-6">
    		<p class="footerSignature">Designed and developed by Eric Atherton</p>
    		@if(Auth::guest())
    		@else
    		<h3 class="footerHeader">Quick Links</h3>
    		<ul class="list-unstyled">
    			<li><a href="{{ url('/home') }}" class="footerLinks"><i class="fa fa-btn fa-chevron-circle-right"></i>Home</a></li>
    			<li><a href="{{ url('/projectIdeas') }}" class="footerLinks"><i class="fa fa-btn fa-chevron-circle-right"></i>All project ideas</a></li>
    			<li><a href="{{ url('/projectExamples') }}" class="footerLinks"><i class="fa fa-btn fa-chevron-circle-right"></i>All project examples</a></li>
    			@if(Auth::user()->accesslevel != 1)
    				<li><a href="{{ url('/users') }}" class="footerLinks"><i class="fa fa-btn fa-chevron-circle-right"></i>All users</a></li>
    			@else 
    				<li><a href="{{ url('/users') }}" class="footerLinks"><i class="fa fa-btn fa-chevron-circle-right"></i>Staff</a></li>
    			@endif
    			@if(Auth::user()->accesslevel == 3)
    				<li><a href="{{ url('/users/create') }}" class="footerLinks"><i class="fa fa-btn fa-chevron-circle-right"></i>Create new user</a></li>
    			@endif
    			@if(Auth::user()->accesslevel != 1)
    				<li><a href="{{ url('/projectIdeas/create') }}" class="footerLinks"><i class="fa fa-btn fa-chevron-circle-right"></i>Submit new project idea</a></li>
    				<li><a href="{{ url('/projectExamples/create') }}" class="footerLinks"><i class="fa fa-btn fa-chevron-circle-right"></i>Submit new project example</a></li>
                    <li><a href="{{ url('/categorys/create') }}" class="footerLinks"><i class="fa fa-btn fa-chevron-circle-right"></i>Add new category</a></li>
    			@endif
    			<li><a href="{{ route('users.edit', [Auth::user()->id]) }}" class="footerLinks"><i class="fa fa-btn fa-chevron-circle-right"></i>Edit account details</a></li>
    		</ul>
    	</div>
        <!-- Provide links that will stick to the top of the footer for accessing the top of the page and logging out. -->
       	<div class="col-md-6">
       		<ul class="footerButtonLinks">
            @if (Auth::user())
           		<li><a href="#" class="footerLinks"><i class="fa fa-btn fa-chevron-circle-up"></i>Return to the top</a></li>
                <li><a href="{{ url('/logout') }}" class="footerLinks"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
            @endif
        	</ul>
        	@endif
       	</div> 
    </div>
</footer>

<!-- JavaScripts - Load jquery and bootstrap JS files -->
<script src="{{ url('js/jquery-2.2.2.min.js') }}"></script>
<script src="{{ url('js/bootstrap.min.js') }}"></script>
<script src="{{ url('js/javascript.js') }}"></script>

resources/views/layouts/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
       <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ url('/home') }}">
                Project Bazaar
            </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">

            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url('/home') }}">Home</a></li>
                <li><a href="{{ url('/projectIdeas') }}">Project Ideas</a></li>
                <li><a href="{{ url('/projectExamples') }}">Project Examples</a></li>
                @if(Auth::guest())
                @else
                    <!-- Provide link based on users access level if they are a student then show staff, if they are staff or an admin show all users. -->
                    @if(Auth::user()->accesslevel != 1)
                        <li><a href="{{ url('/users') }}">All users</a></li>
                    @else
                        <li><a href="{{ url('/users') }}">Staff</a></li>
                    @endif
                @endif
                <!-- Authentication Links -->
                @if (Auth::guest())
                    <li><a href="{{ url('/login') }}">Login</a></li>
                    <li><a href="{{ url('/register') }}">Register</a></li>
                @else
                    <!-- Create dropdown menu using jQuery. Use the logged in users name as the link -->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            {{ Auth::user()->name }} <i class="fa fa-chevron-circle-down"></i>
                        </a>

                        <!-- Dropdown menu contains links for updating account and also logging out. -->
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ route('users.edit', [Auth::user()->id]) }}"><i class="fa fa-btn fa-edit"></i>Update</a></li>
                            <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                    <!-- Show users profile image. -->
                    <li><img src="{{ Auth::user()->profileimage }}" class="profileImage img-circle"></li>
                @endif
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<!-- Produce basic HTML template which will be used by every page. -->
<html lang="en">

	<head>
    	<meta charset="utf-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Get page title from individual pages. -->
    	<title>Project Bazaar - @yield('title')</title>

    	<!-- Fonts -->
    	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
    	<link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel='stylesheet' type='text/css'>

    	<!-- Styles -->
    	<link rel="stylesheet" href="{{ url('css/bootstrap.css' )}}" type="text/css"/>
        <link rel="stylesheet" href="{{ url('css/stylesheet.css' )}}" type="text/css"/>

	</head>

	<body id="app-layout">
        <!-- Load header layout -->
		@include('/layouts/header')
        <!-- Get content from individual pages. -->
    	@yield('content')
        <!-- Load footer layout -->
    	@include('/layouts/footer')
	</body>

</html>